/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.text.SimpleDateFormat;
import dao.ChiTietHoaDonDAO;
import dao.HoaDonDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChiTietHoaDon;
import model.HoaDon;

/**
 *
 * @author duc
 */
public class HoaDonGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HoaDonGUI.class.getName());

    /**
     * Creates new form HoaDonGUI
     */
    public HoaDonGUI() {
        initComponents();
        
        // ĐOẠN CODE ĐỔI LOGO
    try {
        java.awt.Image icon = java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.jpg"));
        this.setIconImage(icon);
    } catch (Exception e) {
        System.out.println("Không tìm thấy ảnh logo!");
    }
    
        loadDataToTable();
        btnMoiActionPerformed(null);
        //tự động điền ngày
        txtNgayLap.setText(new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
        
        //tự động điền mã hóa đơn
        java.text.SimpleDateFormat sdfMa = new java.text.SimpleDateFormat("HHmmss");
        String maTuDong = "HD" + sdfMa.format(new java.util.Date());
        txtMaHD.setEditable(false);
        txtMaHD.setText(maTuDong);
        
    //tự động lấy MaKH & MaSP 
    loadComboBoxKhachHang();
    loadComboBoxSanPham();
    
        tblHoaDon.setDefaultEditor(Object.class, null);
        //tblChiTiet.setDefaultEditor(Object.class, null);
        phanquyen();
        //this.setSize(1000, 700);
        this.setLocationRelativeTo(null);
        this.setTitle("Quản lý Hóa Đơn"); 
        
        // Tự động lấy Mã Nhân Viên từ người đang đăng nhập
if (view.LoginGUI.nguoiDangNhap != null) {
    txtMaNV.setText(view.LoginGUI.nguoiDangNhap.getMaNV());
} else {
    // Dành cho trường hợp bạn lỡ chạy thẳng file HoaDonGUI để test mà không qua Login
    txtMaNV.setText("NV_TEST"); 
}

// Khóa ô nhập lại, không cho người dùng tự ý sửa mã nhân viên
txtMaNV.setEditable(false);
        
    }
    
    private void phanquyen() {
    model.NhanVien nv = view.LoginGUI.nguoiDangNhap;
    if (nv != null && nv.getChucVu().equalsIgnoreCase("Nhân viên")) {
       
        //btnThem.setVisible(false);
        //btnSua.setVisible(false); da xoa
        btnXoa.setVisible(false);
    }
}
    
    public void loadDataToTable() {
    DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
    model.setRowCount(0); 
    List<HoaDon> list = new HoaDonDAO().getAll();
    for (HoaDon hd : list) {
        model.addRow(new Object[]{hd.getMaHD(), hd.getNgayLap(), hd.getMaNV(), hd.getMaKH()});
    }
}
    public void loadChiTietToTable(String maHD) {
    DefaultTableModel model = (DefaultTableModel) tblChiTiet.getModel();
    model.setRowCount(0); 
    
    
    ChiTietHoaDonDAO daoCT = new ChiTietHoaDonDAO();
    List<ChiTietHoaDon> list = daoCT.getDetail(maHD);
    
    for (ChiTietHoaDon ct : list) {
        model.addRow(new Object[]{
            ct.getMaSP(), 
            ct.getSoLuong(), 
            ct.getDonGiaBan(), 
            ct.getSoLuong() * ct.getDonGiaBan() 
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        txtNgayLap = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnThemSP = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        cboMaKH = new javax.swing.JComboBox<>();
        cboMaSP = new javax.swing.JComboBox<>();
        pnlDetail = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChiTiet = new javax.swing.JTable();
        lblTongTien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Ngày lập", "Mã nhân viên", "Mã khách hàng"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jLabel1.setText("Mã Hóa Đơn");

        jLabel2.setText("Ngày Lập");

        jLabel3.setText("Mã Nhân Viên");

        jLabel4.setText("Mã Khách Hàng");

        btnThem.setText("Thêm");
        btnThem.addActionListener(this::btnThemActionPerformed);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);

        btnMoi.setText("Làm mới");
        btnMoi.addActionListener(this::btnMoiActionPerformed);

        txtDonGia.addActionListener(this::txtDonGiaActionPerformed);

        jLabel5.setText("Mã Sản Phẩm");

        jLabel6.setText("Số lượng");

        jLabel7.setText("Đơn giá");

        btnThemSP.setText("Thêm sản phẩm");
        btnThemSP.addActionListener(this::btnThemSPActionPerformed);

        jLabel8.setText("Tìm kiếm");

        txtTimKiem.addActionListener(this::txtTimKiemActionPerformed);
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        cboMaKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboMaSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(85, 85, 85)))
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(txtNgayLap)
                            .addComponent(txtMaNV)))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlHeaderLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlHeaderLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMoi)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXoa)
                                        .addGap(0, 55, Short.MAX_VALUE))
                                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cboMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlHeaderLayout.createSequentialGroup()
                                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(57, 57, 57)
                                .addComponent(cboMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemSP))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHeaderLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4))
                            .addGroup(pnlHeaderLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cboMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnMoi)
                            .addComponent(btnXoa)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(84, 84, 84)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(btnThemSP))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        tblChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Số lượng", "Đơn giá", "Tổng tiền"
            }
        ));
        jScrollPane2.setViewportView(tblChiTiet);

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(255, 51, 51));
        lblTongTien.setText("\"Tổng tiền: 0 VNĐ\"");

        javax.swing.GroupLayout pnlDetailLayout = new javax.swing.GroupLayout(pnlDetail);
        pnlDetail.setLayout(pnlDetailLayout);
        pnlDetailLayout.setHorizontalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTongTien)
                .addContainerGap())
        );
        pnlDetailLayout.setVerticalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTongTien)
                .addContainerGap())
        );

        getContentPane().add(pnlDetail, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
       
    int row = tblHoaDon.getSelectedRow();
    
    
    String maHD = tblHoaDon.getValueAt(row, 0).toString();
    
    
    loadChiTietToTable(maHD);
    
    txtMaHD.setText(tblHoaDon.getValueAt(row, 0).toString());
    txtNgayLap.setText(tblHoaDon.getValueAt(row, 1).toString());
    txtMaNV.setText(tblHoaDon.getValueAt(row, 2).toString());
    
    String maKH_Table = tblHoaDon.getValueAt(row, 3).toString();
   for (int i = 0; i < cboMaKH.getItemCount(); i++) {
    // Nếu item trong ComboBox bắt đầu bằng Mã KH lấy từ bảng
    if (cboMaKH.getItemAt(i).toString().startsWith(maKH_Table + " -")) {
        cboMaKH.setSelectedIndex(i); // Chọn item đó
        break;
    }
}
    tinhTongTien();
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
    
    //txtMaHD.setText("");
    java.text.SimpleDateFormat sdfMa = new java.text.SimpleDateFormat("HHmmss");
String maTuDong = "HD" + sdfMa.format(new java.util.Date());
txtMaHD.setEditable(false);

txtMaHD.setText(maTuDong);
    //txtMaNV.setText("");
    //txtMaKH.setText("");
    if (view.LoginGUI.nguoiDangNhap != null) {
    txtMaNV.setText(view.LoginGUI.nguoiDangNhap.getMaNV());
}
    
    
    if(cboMaKH.getItemCount() > 0) cboMaKH.setSelectedIndex(0);
if(cboMaSP.getItemCount() > 0) cboMaSP.setSelectedIndex(0);
    
    
   // txtMaSP.setText("");
   txtNgayLap.setText(new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
    txtSoLuong.setText("");
    txtDonGia.setText("");
    
    
    DefaultTableModel modelCT = (DefaultTableModel) tblChiTiet.getModel();
    modelCT.setRowCount(0); 
    
    
    txtMaHD.requestFocus();
    tinhTongTien();
    loadDataToTable();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        
    try {
        
        String maHD = txtMaHD.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date ngayDate = sdf.parse(txtNgayLap.getText());
        // Lấy Mã KH từ ComboBox
String selectedKH = cboMaKH.getSelectedItem().toString();
String maKH = selectedKH.split(" - ")[0]; // Cắt lấy phần trước dấu gạch ngang

// Thay txtMaKH.getText() bằng maKH
HoaDon hd = new HoaDon(maHD, ngayDate, txtMaNV.getText(), maKH);

        
        List<ChiTietHoaDon> listCT = new ArrayList<>();
        DefaultTableModel modelCT = (DefaultTableModel) tblChiTiet.getModel();
        
        for (int i = 0; i < modelCT.getRowCount(); i++) {
    
    Object cellMaSP = modelCT.getValueAt(i, 0);
    if (cellMaSP == null || cellMaSP.toString().trim().isEmpty()) {
        continue; 
    }
    
    
    ChiTietHoaDon ct = new ChiTietHoaDon();
    ct.setMaHD(maHD); 
    ct.setMaSP(cellMaSP.toString());
    ct.setSoLuong(Integer.parseInt(modelCT.getValueAt(i, 1).toString()));
    ct.setDonGiaBan(Double.parseDouble(modelCT.getValueAt(i, 2).toString()));
    
    listCT.add(ct);
}    
        if (listCT.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Vui lòng thêm ít nhất 1 sản phẩm vào bảng chi tiết!");
    return; 
}       
        

try (java.sql.Connection conn = util.DBConnection.getConnection()) {
    for (model.ChiTietHoaDon ct : listCT) {
        String sqlCheck = "SELECT SoLuongTon FROM San_Pham WHERE MaSP = ?";
        try (java.sql.PreparedStatement psCheck = conn.prepareStatement(sqlCheck)) {
            psCheck.setString(1, ct.getMaSP());
            java.sql.ResultSet rs = psCheck.executeQuery();
            
            if (rs.next()) {
                int tonKho = rs.getInt("SoLuongTon");
                
                
                if (ct.getSoLuong() > tonKho) {
                    JOptionPane.showMessageDialog(this, 
                        "Thêm thất bại! Sản phẩm " + ct.getMaSP() + " chỉ còn " + tonKho + " cái trong kho.");
                    return; 
                }
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi: Không tìm thấy sản phẩm " + ct.getMaSP() + " trong kho!");
                return; 
            }
        }
    }
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Lỗi khi kết nối CSDL để kiểm tra tồn kho!");
    return;
}


        
        HoaDonDAO dao = new HoaDonDAO();
        if (dao.insert(hd, listCT)) {
            JOptionPane.showMessageDialog(this, "Lưu hóa đơn và chi tiết thành công!");
            loadDataToTable(); 
            btnMoiActionPerformed(null);
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi khi lưu vào Database!");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi dữ liệu: " + e.getMessage());
    }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        // TODO add your handling code here:
        try {
        
        //String maSP = txtMaSP.getText().trim();
        String selectedSP = cboMaSP.getSelectedItem().toString();
String maSP = selectedSP.split(" - ")[0];
        int soLuong = Integer.parseInt(txtSoLuong.getText().trim());
        
        
        if(maSP.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã Sản Phẩm!");
            return;
        }
        
String strDonGia = txtDonGia.getText().trim();
double donGia = 0;

if (strDonGia.isEmpty()) {
    
    try (java.sql.Connection conn = util.DBConnection.getConnection();
         java.sql.PreparedStatement ps = conn.prepareStatement("SELECT DonGia FROM San_Pham WHERE MaSP = ?")) {
        
        ps.setString(1, maSP);
        java.sql.ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            donGia = rs.getDouble("DonGia");
            txtDonGia.setText(String.valueOf(donGia)); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm có mã: " + maSP);
            return; 
        }
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi lấy giá sản phẩm!");
        return;
    }
} else {
    
    donGia = Double.parseDouble(strDonGia);
}
       
        DefaultTableModel model = (DefaultTableModel) tblChiTiet.getModel();
        
       
        model.addRow(new Object[]{
            maSP, 
            soLuong, 
            donGia, 
            soLuong * donGia
        });
        
        
        //txtMaSP.setText("");
        cboMaSP.setSelectedIndex(0);
        txtSoLuong.setText("");
        txtDonGia.setText("");
        //txtMaSP.requestFocus();
        tinhTongTien();
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Số lượng và Đơn giá phải là số!");
    }
     
        
        
       
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        
    String maHD = txtMaHD.getText().trim();
    
   
    if (maHD.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng click chọn một hóa đơn trên bảng để xóa!");
        return;
    }

    
    int xacNhan = JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc chắn muốn xóa toàn bộ hóa đơn " + maHD + " không?", 
            "Xác nhận xóa", 
            JOptionPane.YES_NO_OPTION);
            
    
    if (xacNhan == JOptionPane.YES_OPTION) {
        HoaDonDAO dao = new HoaDonDAO();
        if (dao.delete(maHD)) {
            JOptionPane.showMessageDialog(this, "Đã xóa thành công!");
            loadDataToTable();           
            btnMoiActionPerformed(null); 
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại! Lỗi Database.");
        }
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        
    String keyword = txtTimKiem.getText().trim();
    
   
    HoaDonDAO dao = new HoaDonDAO();
    java.util.List<model.HoaDon> listSearch = dao.search(keyword);
    
    
    DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
    model.setRowCount(0);
    
   
    for (model.HoaDon hd : listSearch) {
        model.addRow(new Object[]{
            hd.getMaHD(), 
            new java.text.SimpleDateFormat("yyyy-MM-dd").format(hd.getNgayLap()), 
            hd.getMaNV(), 
            hd.getMaKH()
        });
    }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HoaDonGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaKH;
    private javax.swing.JComboBox<String> cboMaSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JPanel pnlDetail;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTable tblChiTiet;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
private void tinhTongTien() {
    double tongTien = 0;
    javax.swing.table.DefaultTableModel modelCT = (javax.swing.table.DefaultTableModel) tblChiTiet.getModel();
    
    
    for (int i = 0; i < modelCT.getRowCount(); i++) {
        
        Object cellThanhTien = modelCT.getValueAt(i, 3); 
        if (cellThanhTien != null) {
            tongTien += Double.parseDouble(cellThanhTien.toString());
        }
    }
    
    
    java.text.DecimalFormat df = new java.text.DecimalFormat("#,### VNĐ");
    lblTongTien.setText("Tổng tiền: " + df.format(tongTien));
}

// Hàm lấy dữ liệu Khách Hàng
private void loadComboBoxKhachHang() {
    try (java.sql.Connection conn = util.DBConnection.getConnection();
         java.sql.Statement st = conn.createStatement();
         java.sql.ResultSet rs = st.executeQuery("SELECT MaKH, HoTen FROM Khach_Hang")) {
        
        cboMaKH.removeAllItems(); // Xóa dữ liệu cũ
        while (rs.next()) {
            // Ghép Mã và Tên lại với nhau, ngăn cách bởi chuỗi " - "
            String hienThi = rs.getString("MaKH") + " - " + rs.getString("HoTen");
            cboMaKH.addItem(hienThi); 
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

// Hàm lấy dữ liệu Sản Phẩm
private void loadComboBoxSanPham() {
    try (java.sql.Connection conn = util.DBConnection.getConnection();
         java.sql.Statement st = conn.createStatement();
         java.sql.ResultSet rs = st.executeQuery("SELECT MaSP, TenSP FROM San_Pham")) {
        
        cboMaSP.removeAllItems(); // Xóa dữ liệu cũ
        while (rs.next()) {
            // Ghép Mã và Tên lại với nhau, ngăn cách bởi chuỗi " - "
            String hienThi = rs.getString("MaSP") + " - " + rs.getString("TenSP");
            cboMaSP.addItem(hienThi); 
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
}
