/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duc
 */
public class LoaiSanPhamGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoaiSanPhamGUI.class.getName());

    /**
     * Creates new form NhanVienGUI
     */
    public LoaiSanPhamGUI() {
        initComponents();
        
        // ĐOẠN CODE ĐỔI LOGO
    try {
        java.awt.Image icon = java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.jpg"));
        this.setIconImage(icon);
    } catch (Exception e) {
        System.out.println("Không tìm thấy ảnh logo!");
    }
    
        loadTable(); 
        jTableLoaiSanPham.setDefaultEditor(Object.class, null);
        phanquyen();
        this.setLocationRelativeTo(null);
        this.setTitle("Quản lý Loại Sản Phẩm"); 
    }
    
    private void phanquyen() {
    model.NhanVien nv = view.LoginGUI.nguoiDangNhap;
    if (nv != null && nv.getChucVu().equalsIgnoreCase("Nhân viên")) {
       
        btnThem.setVisible(false);
        btnSua.setVisible(false);
        btnXoa.setVisible(false);
    }
}
    
    public void loadTable() {
    DefaultTableModel model = (DefaultTableModel) jTableLoaiSanPham.getModel();
    model.setRowCount(0); 
    
    dao.LoaiSanPhamDAO dao = new dao.LoaiSanPhamDAO();
    List<model.LoaiSanPham> list = dao.getAll(); 
    
    for (model.LoaiSanPham lsp : list) {
        model.addRow(new Object[]{
            lsp.getMaLoai(), lsp.getTenLoai()
        });
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtMaLSP = new javax.swing.JTextField();
        txtTenLSP = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLoaiSanPham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMaLSP.addActionListener(this::txtMaLSPActionPerformed);

        btnThem.setText("Thêm");
        btnThem.addActionListener(this::btnThemActionPerformed);

        btnSua.setText("Sửa");
        btnSua.addActionListener(this::btnSuaActionPerformed);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);

        jButton4.setText("Làm mới");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jTableLoaiSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã loại sản phẩm", "Tên loại sản phẩm"
            }
        ));
        jTableLoaiSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLoaiSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableLoaiSanPham);

        jLabel1.setText("Mã loại sản phẩm");

        jLabel2.setText("Tên loại sản phẩm");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel7.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addGap(24, 24, 24)
                                        .addComponent(jButton4))
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtMaLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtTenLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaLSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenLSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(jButton4)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
 // TODO add your handling code here:
 
    if (txtMaLSP.getText().isEmpty() || txtTenLSP.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Mã Loại sản phẩm và Tên loại sản phẩm không được để trống!");
        return;
    }

    try {
        
        model.LoaiSanPham lsp = new model.LoaiSanPham();
        lsp.setMaLoai(txtMaLSP.getText());
        lsp.setTenLoai(txtTenLSP.getText());
        
        
       
        
        
        dao.LoaiSanPhamDAO dao = new dao.LoaiSanPhamDAO();
        if (dao.insert(lsp)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm loại sản phẩm thành công!");
            loadTable(); 
            
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm thất bại! Kiểm tra lại mã loại sản phẩm (có thể đã bị trùng).");
        }
     
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
     txtMaLSP.setText("");
    txtTenLSP.setText("");
    
    txtMaLSP.setEnabled(true); 
    loadTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maLSP = txtMaLSP.getText();
    if(maLSP.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Hãy chọn loại sản phẩm để xóa!");
        return;
    }
    
    dao.LoaiSanPhamDAO dao = new dao.LoaiSanPhamDAO();
    if (dao.delete(maLSP)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!");
        loadTable();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại!");
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        
    if (txtMaLSP.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn loại sản phẩm cần sửa từ bảng!");
        return;
    }

    try {
        
        model.LoaiSanPham lsp = new model.LoaiSanPham();
        lsp.setMaLoai(txtMaLSP.getText()); 
        lsp.setTenLoai(txtTenLSP.getText());
        
        
        
        
        
        
        dao.LoaiSanPhamDAO dao = new dao.LoaiSanPhamDAO();
        if (dao.update(lsp)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!");
            loadTable(); 
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Sửa thất bại! Vui lòng kiểm tra lại dữ liệu.");
        }
    }  catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void jTableLoaiSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLoaiSanPhamMouseClicked
        // TODO add your handling code here:
        int row = jTableLoaiSanPham.getSelectedRow(); 
    
    
    txtMaLSP.setText(jTableLoaiSanPham.getValueAt(row, 0).toString());
    txtTenLSP.setText(jTableLoaiSanPham.getValueAt(row, 1).toString());
    
    
    
    txtMaLSP.setEnabled(false);
    }//GEN-LAST:event_jTableLoaiSanPhamMouseClicked

    private void txtMaLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLSPActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
         String keyword = txtSearch.getText(); 
    
    
    dao.LoaiSanPhamDAO dao = new dao.LoaiSanPhamDAO();
    List<model.LoaiSanPham> list = dao.search(keyword);
    
    
    DefaultTableModel model = (DefaultTableModel) jTableLoaiSanPham.getModel();
    model.setRowCount(0);
    for (model.LoaiSanPham lsp : list) {
        model.addRow(new Object[]{
            lsp.getMaLoai(), lsp.getTenLoai()
        });
    }
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoaiSanPhamGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableLoaiSanPham;
    private javax.swing.JTextField txtMaLSP;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenLSP;
    // End of variables declaration//GEN-END:variables
}
