/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author duc
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);//max màn hình
        
        // ĐOẠN CODE ĐỔI LOGO
    try {
        java.awt.Image icon = java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.jpg"));
        this.setIconImage(icon);
    } catch (Exception e) {
        System.out.println("Không tìm thấy ảnh logo!");
    }
    
        phanquyen();
        this.setLocationRelativeTo(null);
        
    }
    
    private void phanquyen() {
    
    model.NhanVien nv = view.LoginGUI.nguoiDangNhap;
    
    if (nv != null) {
        
        if (nv.getChucVu().equalsIgnoreCase("Nhân viên")) {
            
            
            menuNhanVien.setVisible(false);
            //menuNhaCungCap.setVisible(false);
           
            
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNhanVien = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuKhachHang = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuNhaCungCap = new javax.swing.JMenuItem();
        menuLoaiSanPham = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("        Chào mừng bạn đến với hệ thống quản lý");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 447, 277));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rm314-adj-10.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 280));

        jMenu1.setText("Quản lý");

        menuNhanVien.setText("Nhân viên");
        menuNhanVien.addActionListener(this::menuNhanVienActionPerformed);
        jMenu1.add(menuNhanVien);

        jMenuItem3.setText("Sản phẩm");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        menuKhachHang.setText("Khách hàng");
        menuKhachHang.addActionListener(this::menuKhachHangActionPerformed);
        jMenu1.add(menuKhachHang);

        jMenuItem5.setText("Hóa đơn");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu1.add(jMenuItem5);

        menuNhaCungCap.setText("Nhà cung cấp");
        menuNhaCungCap.addActionListener(this::menuNhaCungCapActionPerformed);
        jMenu1.add(menuNhaCungCap);

        menuLoaiSanPham.setText("Loại sản phẩm");
        menuLoaiSanPham.addActionListener(this::menuLoaiSanPhamActionPerformed);
        jMenu1.add(menuLoaiSanPham);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Hệ thống");

        jMenuItem2.setText("Đăng xuất");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu2.add(jMenuItem2);

        jMenuItem6.setText("Thoát");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhanVienActionPerformed

    NhanVienGUI nvGui = new NhanVienGUI();
    nvGui.setVisible(true);
    
   
    nvGui.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);  
    
// TODO add your handling code here:
    }//GEN-LAST:event_menuNhanVienActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
       
    SanPhamGUI spGui = new SanPhamGUI();
    spGui.setVisible(true);
    
   
    spGui.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKhachHangActionPerformed
        // TODO add your handling code here:
        
    KhachHangGUI khGui = new KhachHangGUI();
    khGui.setVisible(true);
    
    
    khGui.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE); 
    }//GEN-LAST:event_menuKhachHangActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        
    HoaDonGUI hdGui = new HoaDonGUI();
    hdGui.setVisible(true);
    
   
    hdGui.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE); 
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
    int xacNhan = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc chắn muốn đăng xuất?", "Xác nhận", 
            javax.swing.JOptionPane.YES_NO_OPTION);
            
    if (xacNhan == javax.swing.JOptionPane.YES_OPTION) {
        
        for (java.awt.Window window : java.awt.Window.getWindows()) {
            window.dispose();
        }
        
        
        new view.LoginGUI().setVisible(true);
        
        
        view.LoginGUI.nguoiDangNhap = null; 
    }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        int xacNhan = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc chắn muốn thoát?", "Xác nhận", 
            javax.swing.JOptionPane.YES_NO_OPTION);
            if (xacNhan == javax.swing.JOptionPane.YES_OPTION)
            {
            System.exit(0);
            }
            
  
    
      
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhaCungCapActionPerformed
        // TODO add your handling code here:
         
    NhaCungCapGUI nccGui = new NhaCungCapGUI();
    nccGui.setVisible(true);
    
    
    nccGui.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE); 
    }//GEN-LAST:event_menuNhaCungCapActionPerformed

    private void menuLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoaiSanPhamActionPerformed
        // TODO add your handling code here:
        LoaiSanPhamGUI lspGui = new LoaiSanPhamGUI();
    lspGui.setVisible(true);
    
   
    lspGui.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuLoaiSanPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem menuKhachHang;
    private javax.swing.JMenuItem menuLoaiSanPham;
    private javax.swing.JMenuItem menuNhaCungCap;
    private javax.swing.JMenuItem menuNhanVien;
    // End of variables declaration//GEN-END:variables
}
