/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duc
 */
public class NhaCungCapGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NhaCungCapGUI.class.getName());

    /**
     * Creates new form NhanVienGUI
     */
    public NhaCungCapGUI() {
        initComponents();
        
        // ĐOẠN CODE ĐỔI LOGO
    try {
        java.awt.Image icon = java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.jpg"));
        this.setIconImage(icon);
    } catch (Exception e) {
        System.out.println("Không tìm thấy ảnh logo!");
    }
    
        loadTable(); 
        jTableNhaCungCap.setDefaultEditor(Object.class, null);
        phanquyen();
        this.setLocationRelativeTo(null);
        this.setTitle("Quản lý Nhà Cung Cấp"); 
    }
    
    private void phanquyen() {
    model.NhanVien nv = view.LoginGUI.nguoiDangNhap;
    if (nv != null && nv.getChucVu().equalsIgnoreCase("Nhân viên")) {
        
        btnThem.setVisible(false);
        btnSua.setVisible(false);
        btnXoa.setVisible(false);
    }
}
    
    public void loadTable() {
    DefaultTableModel model = (DefaultTableModel) jTableNhaCungCap.getModel();
    model.setRowCount(0); 
    
    dao.NhaCungCapDAO dao = new dao.NhaCungCapDAO();
    List<model.NhaCungCap> list = dao.getAll(); 
    
    for (model.NhaCungCap ncc : list) {
        model.addRow(new Object[]{
            ncc.getMaNCC(), ncc.getTenNCC(), ncc.getDiaChi(), ncc.getSdt()
        });
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtMaNCC = new javax.swing.JTextField();
        txtTenNCC = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNhaCungCap = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMaNCC.addActionListener(this::txtMaNCCActionPerformed);

        txtDiaChi.setToolTipText("");

        txtSDT.setToolTipText("");

        btnThem.setText("Thêm");
        btnThem.addActionListener(this::btnThemActionPerformed);

        btnSua.setText("Sửa");
        btnSua.addActionListener(this::btnSuaActionPerformed);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);

        jButton4.setText("Làm mới");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jTableNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "SDT"
            }
        ));
        jTableNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNhaCungCapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableNhaCungCap);

        jLabel1.setText("Mã nhà cung cấp");

        jLabel2.setText("Tên ");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("SDT");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel7.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addGap(24, 24, 24)
                                        .addComponent(jButton4))
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel5)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(jButton4)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
 // TODO add your handling code here:
 
    if (txtMaNCC.getText().isEmpty() || txtTenNCC.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Mã NCC và tên NCC không được để trống!");
        return;
    }

    try {
        
        model.NhaCungCap ncc = new model.NhaCungCap();
        ncc.setMaNCC(txtMaNCC.getText());
        ncc.setTenNCC(txtTenNCC.getText());
        ncc.setDiaChi(txtDiaChi.getText());
        ncc.setSdt(txtSDT.getText());
        
       
        
        
        dao.NhaCungCapDAO dao = new dao.NhaCungCapDAO();
        if (dao.insert(ncc)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm nhà cung cấp thành công!");
            loadTable(); 
            
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm thất bại! Kiểm tra lại mã nhà cung cấp (có thể đã bị trùng).");
        }
     
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
     txtMaNCC.setText("");
    txtTenNCC.setText("");
    txtDiaChi.setText("");
    txtSDT.setText("");
    txtMaNCC.setEnabled(true); 
    loadTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maNCC = txtMaNCC.getText();
    if(maNCC.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Hãy chọn nhà cung cấp để xóa!");
        return;
    }
    
    dao.NhaCungCapDAO dao = new dao.NhaCungCapDAO();
    if (dao.delete(maNCC)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!");
        loadTable();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại!");
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        
    if (txtMaNCC.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà cung cấp cần sửa từ bảng!");
        return;
    }

    try {
       
        model.NhaCungCap ncc = new model.NhaCungCap();
        ncc.setMaNCC(txtMaNCC.getText()); 
        ncc.setTenNCC(txtTenNCC.getText());
        ncc.setDiaChi(txtDiaChi.getText());
        ncc.setSdt(txtSDT.getText());
        
        
        
        
        
        dao.NhaCungCapDAO dao = new dao.NhaCungCapDAO();
        if (dao.update(ncc)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!");
            loadTable(); 
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Sửa thất bại! Vui lòng kiểm tra lại dữ liệu.");
        }
    }  catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void jTableNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNhaCungCapMouseClicked
        // TODO add your handling code here:
        int row = jTableNhaCungCap.getSelectedRow(); 
    
    
    txtMaNCC.setText(jTableNhaCungCap.getValueAt(row, 0).toString());
    txtTenNCC.setText(jTableNhaCungCap.getValueAt(row, 1).toString());
    txtDiaChi.setText(jTableNhaCungCap.getValueAt(row, 2).toString());
    txtSDT.setText(jTableNhaCungCap.getValueAt(row, 3).toString());
    
    
    txtMaNCC.setEnabled(false);
    }//GEN-LAST:event_jTableNhaCungCapMouseClicked

    private void txtMaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNCCActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
       String keyword = txtSearch.getText(); 
    
    
    dao.NhaCungCapDAO dao = new dao.NhaCungCapDAO();
    List<model.NhaCungCap> list = dao.search(keyword);
    
    
    DefaultTableModel model = (DefaultTableModel) jTableNhaCungCap.getModel();
    model.setRowCount(0);
    for (model.NhaCungCap ncc : list) {
        model.addRow(new Object[]{
            ncc.getMaNCC(), ncc.getTenNCC(), ncc.getDiaChi(), ncc.getSdt()
        });
    }
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NhaCungCapGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableNhaCungCap;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenNCC;
    // End of variables declaration//GEN-END:variables
}
