/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duc
 */
public class SanPhamGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SanPhamGUI.class.getName());

    /**
     * Creates new form NhanVienGUI
     */
    public SanPhamGUI() {
        initComponents();
        loadComboBoxLoai();
        loadComboBoxNCC();
        // ĐOẠN CODE ĐỔI LOGO
    try {
        java.awt.Image icon = java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.jpg"));
        this.setIconImage(icon);
    } catch (Exception e) {
        System.out.println("Không tìm thấy ảnh logo!");
    }
    
      loadTable(); 
        jTableSanPham.setDefaultEditor(Object.class, null);
        phanquyen();
        this.setLocationRelativeTo(null);
        this.setTitle("Quản lý Sản Phẩm"); 
        
    }
    
    private void phanquyen() {
    model.NhanVien nv = view.LoginGUI.nguoiDangNhap;
    if (nv != null && nv.getChucVu().equalsIgnoreCase("Nhân viên")) {
        
        btnThem.setVisible(false);
        btnSua.setVisible(false);
        btnXoa.setVisible(false);
    }
}
    
    public void loadTable() {
    DefaultTableModel model = (DefaultTableModel) jTableSanPham.getModel();
    model.setRowCount(0); 
    
    dao.SanPhamDAO dao = new dao.SanPhamDAO();
    List<model.SanPham> list = dao.getAll(); 
    
    for (model.SanPham sp : list) {
        model.addRow(new Object[]{
            sp.getMaSP(), sp.getTenSP(), sp.getDonViTinh(), sp.getDonGia(), sp.getSoLuongTon(), sp.getMaLoai(), sp.getMaNCC()
        });
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtMaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtDonViTinh = new javax.swing.JTextField();
        txtSoLuongTon = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSanPham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboMaLoai = new javax.swing.JComboBox<>();
        cboMaNCC = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSoLuongTon.setToolTipText("");

        btnThem.setText("Thêm");
        btnThem.addActionListener(this::btnThemActionPerformed);

        btnSua.setText("Sửa");
        btnSua.addActionListener(this::btnSuaActionPerformed);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);

        jButton4.setText("Làm mới");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jTableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn vị tính", "Đơn giá", "Số lượng tồn", "Mã loại", "Mã nhà cung cấp"
            }
        ));
        jTableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSanPham);

        jLabel1.setText("Mã sản phẩm");

        jLabel2.setText("Tên sản phẩm");

        jLabel3.setText("Đơn vị tính");

        jLabel4.setText("Đơn giá");

        jLabel5.setText("Số lượng tồn");

        jLabel6.setText("Mã loại");

        txtDonGia.addActionListener(this::txtDonGiaActionPerformed);

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel7.setText("Tìm kiếm");

        jLabel8.setText("Mã nhà cung cấp");

        cboMaLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboMaNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSua)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(1, 1, 1)))
                        .addGap(25, 25, 25)
                        .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(22, 22, 22)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addComponent(cboMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(jButton4)
                    .addComponent(btnSua))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
 // TODO add your handling code here:
 
    if (txtMaSP.getText().isEmpty() || txtTenSP.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Mã SP và Tên sản phẩm không được để trống!");
        return;
    }
    if (txtSoLuongTon.getText().isEmpty() || txtDonGia.getText().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng không để trống số lượng hoặc đơn giá!");
    return;
    }
    
    try {
        
      model.SanPham sp = new model.SanPham();  
        
        
    
    int soLuong = Integer.parseInt(txtSoLuongTon.getText());
    sp.setSoLuongTon(soLuong);
    
    
    double donGia = Double.parseDouble(txtDonGia.getText());
    sp.setDonGia(donGia);
    
   
        sp.setMaSP(txtMaSP.getText());
        sp.setTenSP(txtTenSP.getText());
        sp.setDonViTinh(txtDonViTinh.getText());
        //sp.setMaLoai(txtMaLoai.getText());
        //sp.setMaNCC(txtMaNCC.getText());
        String selectedLoai = cboMaLoai.getSelectedItem().toString();
        sp.setMaLoai(selectedLoai.split(" - ")[0]); // Cắt lấy Mã Loại

         String selectedNCC = cboMaNCC.getSelectedItem().toString();
         sp.setMaNCC(selectedNCC.split(" - ")[0]); // Cắt lấy Mã NCC
        
        dao.SanPhamDAO dao = new dao.SanPhamDAO();
        if (dao.insert(sp)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!");
            loadTable(); 
            
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm thất bại! Kiểm tra lại mã sản phẩm (có thể đã bị trùng).");
        }
             } catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Số lượng hoặc Đơn giá không đúng định dạng số!");
    return; 
             }
        
        
       catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
     txtMaSP.setText("");
    txtTenSP.setText("");
    txtDonViTinh.setText("");
    txtDonGia.setText("");
    txtSoLuongTon.setText("");
    
    //txtMaLoai.setText("");
    //txtMaNCC.setText("");
    if(cboMaLoai.getItemCount() > 0) cboMaLoai.setSelectedIndex(0);
if(cboMaNCC.getItemCount() > 0) cboMaNCC.setSelectedIndex(0);
    
    txtMaSP.setEnabled(true); 
    loadTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maSP = txtMaSP.getText();
    if(maSP.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Hãy chọn sản phẩm để xóa!");
        return;
    }
    
    dao.SanPhamDAO dao = new dao.SanPhamDAO();
    if (dao.delete(maSP)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!");
        loadTable();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại!");
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        
    if (txtMaSP.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần sửa từ bảng!");
        return;
    }

    try {
        
        
      model.SanPham sp = new model.SanPham();  
        
        
    
    int soLuong = Integer.parseInt(txtSoLuongTon.getText());
    sp.setSoLuongTon(soLuong);
    
    
    double donGia = Double.parseDouble(txtDonGia.getText());
    sp.setDonGia(donGia);
    
    
        sp.setMaSP(txtMaSP.getText());
        sp.setTenSP(txtTenSP.getText());
        sp.setDonViTinh(txtDonViTinh.getText());
       
        //sp.setMaLoai(txtMaLoai.getText());
        //sp.setMaNCC(txtMaNCC.getText());
        String selectedLoai = cboMaLoai.getSelectedItem().toString();
         sp.setMaLoai(selectedLoai.split(" - ")[0]); // Cắt lấy Mã Loại

         String selectedNCC = cboMaNCC.getSelectedItem().toString();
        sp.setMaNCC(selectedNCC.split(" - ")[0]); // Cắt lấy Mã NCC
        
        
        dao.SanPhamDAO dao = new dao.SanPhamDAO();
        if (dao.update(sp)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!");
            loadTable(); 
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Sửa thất bại! Vui lòng kiểm tra lại dữ liệu.");
        }
    } 
    catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Số lượng hoặc Đơn giá không đúng định dạng số!");
    return; 
             }
     catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void jTableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSanPhamMouseClicked
        // TODO add your handling code here:
       int row = jTableSanPham.getSelectedRow(); 
    
   
    txtMaSP.setText(jTableSanPham.getValueAt(row, 0).toString());
    txtTenSP.setText(jTableSanPham.getValueAt(row, 1).toString());
    txtDonViTinh.setText(jTableSanPham.getValueAt(row, 2).toString());
    txtDonGia.setText(jTableSanPham.getValueAt(row, 3).toString());
    txtSoLuongTon.setText(jTableSanPham.getValueAt(row, 4).toString());
    
    //txtMaLoai.setText(jTableSanPham.getValueAt(row, 5).toString());
    //txtMaNCC.setText(jTableSanPham.getValueAt(row, 6).toString());
    String maLoaiTable = jTableSanPham.getValueAt(row, 5).toString();
for (int i = 0; i < cboMaLoai.getItemCount(); i++) {
    if (cboMaLoai.getItemAt(i).toString().startsWith(maLoaiTable + " -")) {
        cboMaLoai.setSelectedIndex(i);
        break;
    }
}

String maNCCTable = jTableSanPham.getValueAt(row, 6).toString();
for (int i = 0; i < cboMaNCC.getItemCount(); i++) {
    if (cboMaNCC.getItemAt(i).toString().startsWith(maNCCTable + " -")) {
        cboMaNCC.setSelectedIndex(i);
        break;
    }
}
    

    txtMaSP.setEnabled(false);
    }//GEN-LAST:event_jTableSanPhamMouseClicked

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String keyword = txtSearch.getText(); 
    
    
    dao.SanPhamDAO dao = new dao.SanPhamDAO();
    List<model.SanPham> list = dao.search(keyword);
    
    
    DefaultTableModel model = (DefaultTableModel) jTableSanPham.getModel();
    model.setRowCount(0);
    for (model.SanPham sp : list) {
        model.addRow(new Object[]{
            sp.getMaSP(), sp.getTenSP(), sp.getDonViTinh(), sp.getDonGia(), sp.getSoLuongTon(), sp.getMaLoai(), sp.getMaNCC()
        });
    }
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SanPhamGUI().setVisible(true));
    }
   
    
    private void loadComboBoxLoai() {
    try (java.sql.Connection conn = util.DBConnection.getConnection();
         java.sql.Statement st = conn.createStatement();
         java.sql.ResultSet rs = st.executeQuery("SELECT MaLoai, TenLoai FROM Loai_San_Pham")) {
        
        cboMaLoai.removeAllItems();
        while (rs.next()) {
            cboMaLoai.addItem(rs.getString("MaLoai") + " - " + rs.getString("TenLoai")); 
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

private void loadComboBoxNCC() {
    try (java.sql.Connection conn = util.DBConnection.getConnection();
         java.sql.Statement st = conn.createStatement();
         java.sql.ResultSet rs = st.executeQuery("SELECT MaNCC, TenNCC FROM Nha_Cung_Cap")) {
        
        cboMaNCC.removeAllItems();
        while (rs.next()) {
            cboMaNCC.addItem(rs.getString("MaNCC") + " - " + rs.getString("TenNCC")); 
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaLoai;
    private javax.swing.JComboBox<String> cboMaNCC;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableSanPham;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtDonViTinh;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoLuongTon;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
